
variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.0-dind

stages:
  - build
  - test
  - pre
  - publish

cache:
  key: node_modules
  paths:
    - .npm/
    - node_modules/
    - www/
    - ../vetprovieh-shared
    - ../vetprovieh-pager
    - ../formt-validation
    - ../vetprovieh-detail
    - ../vetprovieh-list
    - ../vetprovieh-select
    - ../vetprovieh-menu

build:
  stage: build

  before_script:
    - npm install
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm run test

publish:
  stage: publish
  image: docker:19.03.0
  before_script:
    - export BASE_IMAGE="mitsgermany/vetprovieh-app"
    - docker login -u $CI_REGISTRY_USER -p$CI_REGISTRY_PASSWORD
  script:
    - export TAGNAME=$BASE_IMAGE":development"
    - echo "1. Publishing Image "$TAGNAME
    - docker build . -t $TAGNAME
    - docker push $TAGNAME
    - export TAGNAME=$BASE_IMAGE":production"
    - echo "1. Publishing Image "$TAGNAME
    - rm ./config/nginx.conf
    - mv ./config/nginx.production.conf ./config/nginx.conf
    - docker build . -t $TAGNAME
    - docker push $TAGNAME
