stages:
  - build
  - test
  - publish

cache:
  key: node_modules
  paths:
    - .npm/

before_script:
  - \[ -d "../vetprovieh-shared/" ] && rm -R ../vetprovieh-shared/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-shared ../vetprovieh-shared
  - \[ -d "../vetprovieh-pager/" ] && rm -R ../vetprovieh-pager/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-pager ../vetprovieh-pager
  - \[ -d "../formt-validation/" ] && rm -R ../formt-validation/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/formt-validation ../formt-validation
  - \[ -d "../vetprovieh-detail/" ] && rm -R ../vetprovieh-detail/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-detail ../vetprovieh-detail
  - \[ -d "../vetprovieh-list/" ] && rm -R ../vetprovieh-list/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-list ../vetprovieh-list
  - \[ -d "../vetprovieh-select/" ] && rm -R ../vetprovieh-select/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-select ../vetprovieh-select
  - \[ -d "../vetprovieh-menu/" ] && rm -R ../vetprovieh-menu/
  - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-menu ../vetprovieh-menu
  
  - npm ci --cache .npm --prefer-offline
  
build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - npm run test

publish:
  stage: publish
  before_script:
    - export TAGNAME="mitsgermany/vetprovieh-app"
    - docker login -u $CI_REGISTRY_USER -p$CI_REGISTRY_PASSWORD
  script:
    - docker build . -t $TAGNAME
    - docker push $TAGNAME
