
variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.0-dind

stages:
  - build
  - test
  - pre
  - publish

cache:
  key: node_modules
  paths:
    - .npm/
    - node_modules/
    - www/
    - ../vetprovieh-shared
    - ../vetprovieh-pager
    - ../formt-validation
    - ../vetprovieh-detail
    - ../vetprovieh-list
    - ../vetprovieh-select
    - ../vetprovieh-menu

build:
  stage: build

  before_script:
    - \[ -d "../vetprovieh-shared/" ] && rm -R ../vetprovieh-shared/
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-shared ../vetprovieh-shared
    - \[ -d "../vetprovieh-pager/" ] && rm -R ../vetprovieh-pager/
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-pager ../vetprovieh-pager
    - cd ../vetprovieh-pager
    - npm install
    - \[ -d "../formt-validation/" ] && rm -R ../formt-validation/
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/formt-validation ../formt-validation
    - cd ../formt-validation
    - npm install
    - \[ -d "../vetprovieh-detail/" ] && rm -R ../vetprovieh-detail/
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-detail ../vetprovieh-detail
    - cd ../vetprovieh-detail
    - npm install
    - \[ -d "../vetprovieh-list/" ] && rm -R ../vetprovieh-list/
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-list ../vetprovieh-list
    - cd ../vetprovieh-list
    - npm install
    - \[ -d "../vetprovieh-select/" ] && rm -R ../vetprovieh-select/
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-select ../vetprovieh-select
    - cd ../vetprovieh-select
    - npm install
    - \[ -d "../vetprovieh-menu/" ] && rm -R ../vetprovieh-menu/
    - git clone https://tomuench:${CI_JOB_TOKEN}@gitlab.edvsz.hs-osnabrueck.de/vetprovieh/core/web-application/vetprovieh-menu ../vetprovieh-menu
    - cd ../vetprovieh-menu
    - npm install
    - cd ../vetprovieh-app
  script:
    - npm ci --cache .npm --prefer-offline
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm run test

publish:
  stage: publish
  image: docker:19.03.0
  before_script:
    - export BASE_IMAGE="mitsgermany/vetprovieh-app"
    - docker login -u $CI_REGISTRY_USER -p$CI_REGISTRY_PASSWORD
  script:
    - export TAGNAME=$BASE_IMAGE":development"
    - echo "1. Publishing Image "$TAGNAME
    - docker build . -t $TAGNAME
    - docker push $TAGNAME
    - export TAGNAME=$BASE_IMAGE":production"
    - echo "1. Publishing Image "$TAGNAME
    - rm ./config/nginx.conf
    - mv ./config/nginx.production.conf ./config/nginx.conf
    - docker build . -t $TAGNAME
    - docker push $TAGNAME
